services:
  - type: web
    name: tailor2-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TAILOR2_DATABASE_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0 